apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-stateset 
  namespace: test-stateset 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-stateset
  serviceName: test-stateset-websrv 
  template:
    metadata:
      labels:
        app: test-stateset
    spec:
      containers:
      - image: k8s.gcr.io/test-webserver
        imagePullPolicy: Always
        name: test-stateset-pod
        volumeMounts:
        - mountPath: /test
          name: test-stateset-pvc
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: test-stateset-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 1Gi
